### PR TITLE
Adds grid layout component, events, and news page. Fix for bug in New…

### LINKED ISSUE #26: Add events list page
A page that lists every event and provides a link to their pages.

### LINKED ISSUE #40: Add News List page
Create a CardList component that will list PageCard components as a Chakra-ui SimpleGrid.
Should be resusable for events as well.

### PR DESCRIPTION
**Pull request by jaredscarr**
The PR adds a new CardList component that will render any card that fits the ListItem interface. It is responsive and will show a single row on smaller screens and 3 cards per row on larger screens. Description on the PageCard was truncated to 2 lines to better ensure that the cards are the same size. However if someone does add a one liner description then it will look wonky. Just don't do that.

Added:
- News responsive grid layout
- Events responsive grid layout
- PageCard updated for consistency
- Switch from unix timestamps to string datesfor easier re-use of existing components

Bug Fix:
- id added to news object in News.ts so it renders

### CODE REVIEW

File: components/ItemList/CardList.tsx [hunk 1]
```diff
@@ -0,0 +1,40 @@
+import React from "react";
+import { SimpleGrid } from "@chakra-ui/react";
+import PageCard from "../PageCard/PageCard";
+
+/** The data needed for a news card. */
+export interface listItem {
```
Comment (uellenberg) [inline components/ItemList/CardList.tsx]: Nitpick/Style, but the first letter should be capitalized for interfaces (and types and classes)

File: components/ItemList/CardList.tsx [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+    /** The news item's description. */
+    description: string;
+}
+
+/**
+ * A SimpleGrid layout that holds PageCards.
+ * Will work with any object that fits the listItem interface.
+ * @param listItems {} - list of items to display in grid.
+ */
+const CardList = ({ listItems }: { listItems: listItem[] }) => {
```
Comment (uellenberg) [inline components/ItemList/CardList.tsx]: Just to clarify the above comment, this should be `const CardList = ({ listItems }: { listItems: ListItem[] }) => {`

File: pages/events.tsx [hunk 3]
```diff
@@ -0,0 +1,47 @@
...
+
+/**
+ * Events page that displays n events where n is the count passed to getEventCards within getServerSideProps.
+ * @param events
+ * @constructor
+ */
+const Events = ({ events }: { events: EventCard[] }) => {
+  return (
+    <>
+      <SEO url="https://northcs.org" />
```
Comment (uellenberg) [inline pages/events.tsx]: This URL isn't correct.

File: pages/news.tsx [hunk 4]
```diff
@@ -0,0 +1,47 @@
...
+
+/**
+ * Events page that displays n events where n is the count passed to getNewsCards within getServerSideProps.
+ * @param news
+ * @constructor
+ */
+const News = ({ news }: { news: NewsCard[] }) => {
+    return (
+        <>
+            <SEO url="https://northcs.org" />
```
Comment (uellenberg) [inline pages/news.tsx]: Same as above. Should be `https://northcs.org/news`.

File: components/ItemList/CardList.tsx [hunk 5]
```diff
@@ -0,0 +1,40 @@
...
+    return (
+        <SimpleGrid columns={{ sm: 1, md: 1, lg: 3 }} spacing={10} m={20}>
+            {listItems.map((listItem) => (
+                <PageCard
+                    key={listItem.id}
+                    title={listItem.title}
+                    time={new Date(listItem.date)}
+                    description={listItem.description}
+                    url={"/news/" + listItem.id}
```
Comment (uellenberg) [inline components/ItemList/CardList.tsx]: This only works for news items, but is being used for events as well. I'd recommend either not using a separate component, or getting the pagecards from the parent (by doing `const CardList: React.FC<PropsWithChildren>`, accepting `children` instead of `listItems`, and putting children inside of the grid like `<SimpleGrid ...>{children}</SimpleGrid>`).

Also, just as a more general but related note, I'd recommend using `React.FC<Props>` instead of `({ myProp}: Props)` (so at the end, `const MyComponent: React.FC<Props> = ({ myProp }) => ...`) because it lets the type checker know what type the function should return. Up to you though - it's not really that important.

File: lib/Event.ts [hunk 6]
```diff
@@ -1,7 +1,10 @@
-import { DAY, redisClient } from "./redis";
+import { HOUR, redisClient } from "./redis";
 
 /** The data needed for an event card. */
 export interface EventCard {
+    /** id */
+    id: number;
+
```
Comment (uellenberg) [inline lib/Event.ts]: This is here to make CardList work, right? If make the cards determined by the parent component, then you don't need this.

**Review by uellenberg — CHANGES_REQUESTED** [review]
Thanks Jared, looks good! I added a couple comments, but the most important is is the CardList stuff.
